---
title: "Working with Data"
---

## Reading in Data

This section discusses reading in and manipulating stored in files.

There are many, many different libraries to manipulate various formats of text and binary files. Here we shall look only at the built-in Julia methods, and the most popular package for reading in large amounts of data - CSV.jl.

For cases where you may want to store binary data (such as storing variables to file), the JLD2^[The data is stored in a format compatible with the HDF5 standard and the package and read most files created by other programs in HDF5 format. HDF, or Hierarchical Data Format is a standard created by the US National Center for Supercomputing Applications.] package is very convenient.


For processing the data, there are again a near-infinite number of options. The most popular, and extremely powerful, choice is to put the data in a DataFrame object. 

### Using Files in Julia
#### Open, Read and Write
You can do simple file access through base the Julia commands `open` and `write`:

```julia
write(filename, x) # Where filename is a string literal or variable with the full filename.
write(io, x, y...) # Where io is a file handle from open()
```
### FileIO and JLD2

### The DelimitedFiles Standard Library

### CSV.jl

## DataFrames

