project:
  type: website

website:
  title: "Julia for Engineering Research"
  back-to-top-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - 01_Getting_started_with_Julia.qmd
      - 02_Installing_Julia.qmd
      - 03_Running_Julia.qmd
      - 04_An_Overview_of_the_Language.qmd
      - 05_Plotting.qmd
      - 06_Solving_Linear_Systems.qmd
      - 07_Solving_Non-linear_Systems.qmd
      - 08_Solving_Differential_Equations.qmd
      - 09_Optimisation.qmd
      - 10_Automatic_Differentiation.qmd
      - 11_Modelling_Toolkit_and_Symbolics.qmd
      - 12_Working_with_Data.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    monofont: "JetBrains Mono"
    embed-resources: true
